### ISSUE TITLE
Fails with JPG input file for VideoThumbGenerator service

### ISSUE THREAD

**Issue by lookingdown** [soluble-io/soluble-mediatools#8]
These 2 additions to
src/Video/VideoThumbGenerator.php 
Makes thumbgenerator silently fail with JPG as input file...
I find this library extremely useful and potentially a universal goto solution for high quality filters for BOTH image files (tested with JPG worked fine before) would be great if compatibility with jpg as input could be kept ..  Thanks a lot for a great tool..

Additions that lead to failing output of thumbnail..:
line 73 $timeParams = (new VideoConvertParams())->withSeekStart(
            $thumbParams->getParam(VideoThumbParamsInterface::PARAM_SEEK_TIME)
        );

line 108 $adapter->getMappedConversionParams($timeParams)

**Comment by belgattitude** [comment]
Interesting... I've never imagined such an use. 

Out of curiosity, do you have an example with filters you could use ?

Getting late here, but I'll try to find a solution very soon

**Comment by lookingdown** [comment]
Just use a jpg file for input and set time (0)
version <=0.76 .. add filter or chained filters..

**Comment by belgattitude** [comment]
wow, incredible ;)  

You're right the time is required...  I need a good sleep on that, but what you're doing with filters looks great !

For now, I've just added a functional case based on `VideoConversionService` which will do the job.

```php
<?php
$convertParams = (new VideoConvertParams())
    ->withVideoCodec('mjpeg')
    ->withVideoFilter(new VideoFilterChain(
        [
            new ScaleFilter(320, 200),
            new Hqdn3DVideoFilter()
        ]
    ))
    ->withVideoQualityScale(2);

$this->videoConvert->convert($this->imgFile, $outputFile, $convertParams);
```

You can have a look: https://github.com/soluble-io/soluble-mediatools/commit/5f16b8b64446dc1ff8d46076d0b39b1381e69899

Thanks a lot... Let's keep in touch.

**Comment by belgattitude** [comment]
After a good night, here's some thoughts:

I would like to keep `VideoThumbGenerator` as specific as possible. I must admit I'm not happy with it's current API. I would love to add support for strategies (see [here](https://github.com/soluble-io/soluble-mediatools/blob/master/docs/ideas.md), multiple thumbnails, scene selection...), but I need time to figure out how to architect it (use of facade, helpers, presets ?) I will publish an RFC soon asking for reviews. 

So I suggest to use the `VideoConverter` service with the mjpeg encoder for now. Note also that I'll probably simplify the seektime param soon (a float looks better to me) add support for grepping the console output and document how logger works.

Let me know if it's fine for you and thanks !

FYI: video filter doc update; https://soluble-io.github.io/soluble-mediatools/video-filters/

**Comment by belgattitude** [comment]
Closed in favour of using VideoConverter service with mjpeg filter... Feel free to reopen
